const TODOS = {
    LOAD: 'TODOS_LOAD',
    LOAD_SUCCESS: 'TODOS_LOAD_SUCCESS',
    LOAD_FAIL: 'TODOS_LOAD_FAIL',
    POST: 'LOAD_POST',
    POST_SUCCESS: 'POST_SUCCESS',
    POST_FAIL: 'POST_FAIL',
    DELETE: 'LOAD_DELETE',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAIL: 'DELETE_FAIL',
    PUT: 'LOAD_PUT',
    PUT_SUCCESS: 'PUT_SUCCESS',
    PUT_FAIL: 'PUT_FAIL'

}

const USERS = {
    LOGIN: 'LOGIN_LOAD',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT_LOAD',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL'
}

const SESSION = {
    LOAD_SESSION: 'LOAD_SESSION',
    LOAD_SESSION_SUCCESS: 'LOAD_SESSION_SUCCESS',
    LOAD_SESSION_FAIL: 'LOAD_SESSION_FAIL',
    LOAD_REFRESH: 'LOAD_REFRESH',
    REFRESH: 'REFRESH'
}

export { TODOS, USERS, SESSION }
